baseURL = "https://friendly-praline-35ae31.netlify.app/"
languageCode = "en-us"
title = "Daniel KW | Geo Corner"


[params]
  author = "Daniel KW"
  description = "Researcher in Spatial Analytics and Geospatial Science"
  subtitle = "Spatial Analytics · Geographic Information Science · Remote Sensing . Environment"
  email = "daniel_kassahun@yahoo.com"
  twitter = ""
  github = ""
  linkedin = ""

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Research"
    url = "/research/"
    weight = 2
  [[menu.main]]
    name = "Opinion"
    url = "/opinions/"
    weight = 3
  [[menu.main]]
    name = "CV"
    url = "/cv/"
    weight = 4

[taxonomies]
  tag = "tags"
  category = "categories"
